backend:
  name: github
  repo: piecyk/netlifycmsHello
  branch: master
  base_url: http://127.0.0.1:8089

media_folder: "public/assets/static/uploads"

collections:

  - name: "posts"
    label: "Posts"
    folder: "public/assets/_posts"
    slug: "{{slug}}"
    create: true
    format: "json"
    editor:
      preview: false
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Image2", name: "image2", widget: "githubImage"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "settings"
    label: "Settings"
    delete: false
    editor:
      preview: false
    files:
      - name: "general"
        label: "Site Settings"
        file: "_data/settings.json"
        description: "General Site Settings"
        fields:
          - {label: "Global title", name: "site_title", widget: "string"}
          - {label: "Number of posts on frontpage", name: front_limit, widget: number}
